language: node_js

node_js:
  - "10"

branches:
  only:
    - master

env:
  global:
    - TF_VERSION=0.11.10

before_install:
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
  - terraform --version
  - yarn check:ci
