language: node_js

node_js:
  - "10"

branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

script:
  - terraform --version
  - yarn check:ci
